name: DevSecOps Pipeline Cloud

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  unit-test:
    name: Tests unitaires et couverture
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Installer Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests
        run: npm test

      - name: Sauvegarder la couverture
        uses: actions/upload-artifact@v7
        with:
          name: coverage
          path: coverage/

  sonar-check:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Récupérer la couverture
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage/

      - name: Vérifier la configuration Sonar
        run: cat sonar-project.properties

      - name: Analyse SonarQube Cloud
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.qualitygate.wait=true

  dependency-scan:
    name: Scan des dépendances avec Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Scan du système de fichiers
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'

  build-image:
    name: Build de l'image Docker
    needs: [ sonar-check, dependency-scan ]
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Build de l'image
        run: docker build -t my-app:${{ github.sha }} .

      - name: Exporter l'image
        run: docker save my-app:${{ github.sha }} -o my-image.tar

      - name: Sauvegarder l'image Docker
        uses: actions/upload-artifact@v7
        with:
          name: docker-image
          path: my-image.tar

  container-scan:
    name: Scan de l'image Docker avec Trivy
    needs: build-image
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer l'image Docker
        uses: actions/download-artifact@v8
        with:
          name: docker-image
          path: .

      - name: Charger l'image
        run: docker load -i my-image.tar

      - name: Scanner l'image Docker
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: 'image'
          image-ref: 'my-app:${{ github.sha }}'
          severity: 'CRITICAL'
          exit-code: '1'
